spring.application.name=eventos

# GENERAL
server.port=8081

# CONEXION A MYSQL XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/enexia?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
spring.datasource.username=root
spring.datasource.password=

server.tomcat.relaxed-query-characters=|<>[]{}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ====================================================================================
# CONFIGURACIÓN DE TIEMPO DE VIDA DE LA SESIÓN
# ====================================================================================

# Establece la duración máxima de la sesión a 5 minutos de inactividad.
# El formato acepta minutos ('m'), segundos ('s'), u horas ('h').
server.servlet.session.timeout=30m


#spring.security.user.name=miusuario
#spring.security.user.password=miclave



# ====================================================================================
# CONFIGURACIÓN DE CORREO (GMAIL REAL)
# ====================================================================================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}

# Seguridad SSL para Puerto 465 (El más estable en nubes)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=${MAIL_PORT}
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory


spring.main.cloud-platform=NONE
java.net.preferIPv4Stack=true

# Subimos el tiempo a 15 segundos para la nube
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

# Tu link real para recuperar clave
app.base-url=${APP_URL}


